// AUTO-GENERATED by QA UI App. Edits will be overwritten on every settings change.
// .env files in this workspace are loaded by the runner and injected into
// process.env before Playwright spawns, so they're available everywhere
// (including inside auth.setup.ts) without needing to import dotenv here.
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: "/private/tmp/claude-501/-Volumes-WD-Black-SN850X-Desktop-Taller-QA-UI-App/13e31d28-89d4-4462-b342-785339dfaec3/scratchpad/next-data/workspaces/t_WuiNvAeC9ySK0e",
  testIgnore: ['**/reference_repo/**'],
  fullyParallel: false,
  workers: 1,
  retries: 0,
  reporter: 'json',
  use: {
    baseURL: "https://github.com/acmecorptallerqa-tech/todo-list",
    headless: true,
    screenshot: 'on',
    video: 'on',
    trace: 'on',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
});
